version: "3.2"

services:
  a2sketch:
    build:
      context: .
    image: "arne/a2sketch:0.12"
    volumes:
      - type: bind
        source: ./a2s-custom-types
        target: /custom-types
        read_only: true
    ports:
      - "22753:22753"

    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - type: bind
        source: .
        target: /home/node
        #read_only: true
