version: "3.2"

services:
  a2sketch:
    build:
      args:
        version: "0.11"
      context: .
      dockerfile: Dockerfile
    image: "arne/a2sketch:0.11"
    volumes:
      - type: bind
        source: ./a2s-custom-types
        target: /custom-types
        read_only: true
    ports:
      - "22753:22753"
